const w = require('./n8n/workflow_generate_forms.json');

console.log('');
console.log('✅ WORKFLOW FIXED - READY FOR n8n');
console.log('');
console.log('DATABASE SCHEMA MAPPING:');
console.log('Supabase forms table:');
console.log('  user_id (UUID)');
console.log('  title (text) - from form_title');
console.log('  slug (text) - auto-generated slug_timestamp');
console.log('  status (text) - "published"');
console.log('  form_structure (JSONB)');
console.log('    - form_title');
console.log('    - form_description');
console.log('    - questions[]');
console.log('    - sections[]');
console.log('    - thank_you_title');
console.log('    - thank_you_description');
console.log('  ai_config (JSONB)');
console.log('  consultant_email (text)');
console.log('  consultant_name (text)');
console.log('  consultant_role (text)');
console.log('  domain (text)');
console.log('  views_count (integer)');
console.log('  leads_count (integer)');
console.log('');
console.log('✅ DATA FLOW:');
console.log('1. Webhook receives user_id, user_email, consultant_profile');
console.log('2. Validate Input: checks prompt field');
console.log('3. Prepare Prompt: builds Gemini context');
console.log('4. Gemini generates: form_title, form_description, questions, thank_you titles');
console.log('5. Parse JSON: extracts all fields');
console.log('6. Prepare Data for DB: transforms to Supabase schema');
console.log('   - form_structure stored as JSON');
console.log('   - slug auto-generated');
console.log('   - consultant_email from user_email');
console.log('7. Save to Supabase: inserts with all fields');
console.log('8. Response webhook: confirms success');
console.log('');
console.log('✅ READY TO IMPORT INTO n8n!');
