-- Migration 10 — Shared Schema: Platform Linking Architecture
-- Creates the bridge layer between WhatsApp CRM and Consultant CRM.
-- All tables live in the `shared` schema (separate from `public`) so that
-- both apps query them without naming collisions.

CREATE SCHEMA IF NOT EXISTS shared;

-- ─────────────────────────────────────────────────────────────
-- 1. shared.contacts
--    Canonical identity record — linked by phone (primary key)
--    and/or email across both apps.
--    A row here means "this person exists in the pretalk ecosystem."
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS shared.contacts (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id       UUID NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,

  -- Identity pivots
  phone           TEXT,
  email           TEXT,
  full_name       TEXT,
  avatar_url      TEXT,

  -- Cross-app references (nullable — set when the contact exists in that app)
  wa_contact_id   UUID REFERENCES public.contacts(id)  ON DELETE SET NULL,
  crm_lead_id     UUID,   -- references consultant.leads(id) — set by consultant app

  -- Metadata
  source          TEXT DEFAULT 'whatsapp'
                  CHECK (source IN ('whatsapp', 'consultant', 'form', 'import', 'api')),
  tags            TEXT[]  DEFAULT '{}',
  created_at      TIMESTAMPTZ DEFAULT now(),
  updated_at      TIMESTAMPTZ DEFAULT now(),

  -- A contact is unique per tenant by phone OR email
  UNIQUE (tenant_id, phone),
  UNIQUE (tenant_id, email)
);

CREATE INDEX IF NOT EXISTS idx_shared_contacts_tenant   ON shared.contacts(tenant_id);
CREATE INDEX IF NOT EXISTS idx_shared_contacts_wa       ON shared.contacts(wa_contact_id) WHERE wa_contact_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_shared_contacts_crm      ON shared.contacts(crm_lead_id)   WHERE crm_lead_id   IS NOT NULL;

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION shared.set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$;

DROP TRIGGER IF EXISTS trg_shared_contacts_updated_at ON shared.contacts;
CREATE TRIGGER trg_shared_contacts_updated_at
  BEFORE UPDATE ON shared.contacts
  FOR EACH ROW EXECUTE FUNCTION shared.set_updated_at();

-- ─────────────────────────────────────────────────────────────
-- 2. shared.engagements
--    Abstract commercial dossier that can originate from either app.
--    WhatsApp: a lead generated from a conversation (mode_freelance).
--    Consultant: a full project/mission.
--    This is the bridge that gives both apps a common "deal" view.
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS shared.engagements (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id       UUID NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  contact_id      UUID REFERENCES shared.contacts(id) ON DELETE SET NULL,

  -- Origin
  source_app      TEXT NOT NULL DEFAULT 'whatsapp'
                  CHECK (source_app IN ('whatsapp', 'consultant')),
  source_id       UUID,           -- conversation_id (WA) or lead_id (consultant)

  -- Status — unified 4-step freelance mini-pipeline
  status          TEXT NOT NULL DEFAULT 'discovery'
                  CHECK (status IN ('discovery', 'proposed', 'signed', 'invoiced', 'lost')),

  title           TEXT,
  description     TEXT,
  amount          NUMERIC(12, 2),
  currency        TEXT DEFAULT 'MAD',

  -- Dates
  started_at      TIMESTAMPTZ DEFAULT now(),
  proposed_at     TIMESTAMPTZ,
  signed_at       TIMESTAMPTZ,
  invoiced_at     TIMESTAMPTZ,
  closed_at       TIMESTAMPTZ,

  created_at      TIMESTAMPTZ DEFAULT now(),
  updated_at      TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_shared_engagements_tenant  ON shared.engagements(tenant_id);
CREATE INDEX IF NOT EXISTS idx_shared_engagements_contact ON shared.engagements(contact_id);
CREATE INDEX IF NOT EXISTS idx_shared_engagements_status  ON shared.engagements(tenant_id, status);

DROP TRIGGER IF EXISTS trg_shared_engagements_updated_at ON shared.engagements;
CREATE TRIGGER trg_shared_engagements_updated_at
  BEFORE UPDATE ON shared.engagements
  FOR EACH ROW EXECUTE FUNCTION shared.set_updated_at();

-- ─────────────────────────────────────────────────────────────
-- 3. shared.documents
--    Unified storage for proposals, contracts, and invoices.
--    Generated by either app; accessible from both.
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS shared.documents (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id       UUID NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  engagement_id   UUID REFERENCES shared.engagements(id) ON DELETE SET NULL,
  contact_id      UUID REFERENCES shared.contacts(id)    ON DELETE SET NULL,

  type            TEXT NOT NULL
                  CHECK (type IN ('proposal', 'contract', 'invoice', 'quote', 'other')),
  status          TEXT NOT NULL DEFAULT 'draft'
                  CHECK (status IN ('draft', 'sent', 'signed', 'paid', 'cancelled')),

  title           TEXT NOT NULL,
  reference       TEXT,           -- e.g. DEVIS-2026-001
  amount          NUMERIC(12, 2),
  currency        TEXT DEFAULT 'MAD',

  -- Storage
  storage_path    TEXT,           -- Supabase storage path
  public_url      TEXT,

  -- Source tracking
  created_by_app  TEXT DEFAULT 'consultant'
                  CHECK (created_by_app IN ('whatsapp', 'consultant')),
  created_by      UUID REFERENCES public.users(id) ON DELETE SET NULL,

  sent_at         TIMESTAMPTZ,
  signed_at       TIMESTAMPTZ,
  paid_at         TIMESTAMPTZ,
  created_at      TIMESTAMPTZ DEFAULT now(),
  updated_at      TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_shared_documents_tenant     ON shared.documents(tenant_id);
CREATE INDEX IF NOT EXISTS idx_shared_documents_engagement ON shared.documents(engagement_id);
CREATE INDEX IF NOT EXISTS idx_shared_documents_contact    ON shared.documents(contact_id);
CREATE INDEX IF NOT EXISTS idx_shared_documents_type       ON shared.documents(tenant_id, type, status);

DROP TRIGGER IF EXISTS trg_shared_documents_updated_at ON shared.documents;
CREATE TRIGGER trg_shared_documents_updated_at
  BEFORE UPDATE ON shared.documents
  FOR EACH ROW EXECUTE FUNCTION shared.set_updated_at();

-- ─────────────────────────────────────────────────────────────
-- 4. tenants — add mode_freelance flag
--    When true, the WhatsApp app shows the freelance mini-pipeline
--    (Créer Devis button in ChatPanel, /service-cases page, etc.)
-- ─────────────────────────────────────────────────────────────
ALTER TABLE public.tenants
  ADD COLUMN IF NOT EXISTS mode_freelance BOOLEAN DEFAULT false;

-- ─────────────────────────────────────────────────────────────
-- 5. RLS — grant authenticated users access to shared schema
-- ─────────────────────────────────────────────────────────────
ALTER TABLE shared.contacts    ENABLE ROW LEVEL SECURITY;
ALTER TABLE shared.engagements ENABLE ROW LEVEL SECURITY;
ALTER TABLE shared.documents   ENABLE ROW LEVEL SECURITY;

-- shared.contacts
DROP POLICY IF EXISTS shared_contacts_tenant_isolation ON shared.contacts;
CREATE POLICY shared_contacts_tenant_isolation ON shared.contacts
  FOR ALL TO authenticated
  USING (
    tenant_id IN (
      SELECT t.id FROM public.tenants t
      JOIN public.users u ON u.tenant_id = t.id
      WHERE u.id = auth.uid()
    )
  );

-- shared.engagements
DROP POLICY IF EXISTS shared_engagements_tenant_isolation ON shared.engagements;
CREATE POLICY shared_engagements_tenant_isolation ON shared.engagements
  FOR ALL TO authenticated
  USING (
    tenant_id IN (
      SELECT t.id FROM public.tenants t
      JOIN public.users u ON u.tenant_id = t.id
      WHERE u.id = auth.uid()
    )
  );

-- shared.documents
DROP POLICY IF EXISTS shared_documents_tenant_isolation ON shared.documents;
CREATE POLICY shared_documents_tenant_isolation ON shared.documents
  FOR ALL TO authenticated
  USING (
    tenant_id IN (
      SELECT t.id FROM public.tenants t
      JOIN public.users u ON u.tenant_id = t.id
      WHERE u.id = auth.uid()
    )
  );

-- ─────────────────────────────────────────────────────────────
-- 6. Helper RPC: upsert a shared contact from a WA contact
-- ─────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION shared.sync_wa_contact(
  p_tenant_id   UUID,
  p_wa_contact_id UUID,
  p_phone       TEXT,
  p_email       TEXT DEFAULT NULL,
  p_full_name   TEXT DEFAULT NULL,
  p_avatar_url  TEXT DEFAULT NULL
)
RETURNS UUID
LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_id UUID;
BEGIN
  INSERT INTO shared.contacts (tenant_id, wa_contact_id, phone, email, full_name, avatar_url, source)
  VALUES (p_tenant_id, p_wa_contact_id, p_phone, p_email, p_full_name, p_avatar_url, 'whatsapp')
  ON CONFLICT (tenant_id, phone) DO UPDATE SET
    wa_contact_id = EXCLUDED.wa_contact_id,
    email         = COALESCE(EXCLUDED.email,      shared.contacts.email),
    full_name     = COALESCE(EXCLUDED.full_name,  shared.contacts.full_name),
    avatar_url    = COALESCE(EXCLUDED.avatar_url, shared.contacts.avatar_url),
    updated_at    = now()
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$$;

GRANT EXECUTE ON FUNCTION shared.sync_wa_contact TO authenticated;
